### ISSUE TITLE
KISS_HOOK: Ad a hook to manipulate dependencies 

### ISSUE THREAD

**Issue by sdsddsd1** [kiss-community/kiss#28]
The hooks we currently have in `pkg_build()`, hook in right after the dependencies have been resolved. https://github.com/kiss-community/kiss/blob/master/kiss#L681 This makes it impossible to manipulate the depends file.  
My idea is to do something like in this repository. https://github.com/eudaldgr/kiss-garbage/blob/master/gfx/README.md

My specific scenario is running a wayland only build without X-libraries installed. This makes it necessary to fork 11 some thing packages. Most of them is just to remove items from the depends file. 

This issue should track if it can be useful feature, and if others would use it.  
I am also looking into the future, if this hook can be an valuable option towards wayland compatibility, while leaving the official repositories untouched and dont deal with forks.

I played around with kiss but my shellskills are not sufficient to implement this myself.

**Comment by cemkeylan** [comment]
I can't think of a way of doing this without making it ugly. Build files aren't extracted until you enumerate dependencies, so you can't make temporary changes to the `depends` file. One way of doing it would be adding a hook before dependency enumeration so you can change the dependencies, and restore the file after it.

_However_, here is a better non-ugly way of doing it. Just change the dependency and commit into the repository. That is what I am doing on the KISS community repository, because the community repository has a package named `lcms` which is packaged as `lcms2` on Carbs.

If you are annoyed by git opening an editor for the merge commit message (I am), you can call it as `GIT_EDITOR=true kiss u`.

If you are contributing to the repository, you can create branches with `git branch new-package-version origin/master` so that it doesn't push your local commits outside.

**Comment by dilyn-corner** [comment]
> My specific scenario is running a wayland only build without X-libraries installed. This makes it necessary to fork 11 some thing packages. Most of them is just to remove items from the depends file.

BUT this is precisely the point of `kiss-fork`.

**Comment by TAAPArthur** [comment]
So this idea would be beneficial to me. My use case would be to swap out library implementation like switching from lijpeg-turbo to libjpeg because cmake is evil. I've just been forking the package to remove the dependency which isn't too terrible. 

But off the top of my head here are some options we could do (I'm not claiming all of these are good)

1. Fork the package and manually modify the depends file. It's already been said and is obvious but just stating it for completeness. Instead of committing directly on the upstream repo I just have a local one that I give precedence to. If it is just updating the depends file, you can link the other file to not have to manually change the version. Maybe it is worth having wrapper that does `kiss-fork` and `kiss-link` for a files in the repro
2. Fork the package you want to remove and make it a no-op (empty build) or make it a link to the desired package (probably want to avoid non-static binary packages like in repo-bin)
3. Augment kiss to run a command over the depends file every time it reads it. Like instead of `while read do .. done <depends` it is `${KISS_DEPEND_HOOK:-cat} depends | while read; do ... done`. A `sed` with our desired regex handle both the use cases presented here. For example, `KISS_DEPEND_HOOK="sed s/lijpeg-turbo/libjpeg/"`
4. Have git-hook that just updates the depend files on git pull. And then throw these changes away before a pull

I think (3) is decently clean and covers the targeted case while probably extending well to others. Spawns an extra process but who's counting.

**Comment by sdsddsd1** [comment]
Thank you for suggestions, and @cemkeylan for showing of an alternative way to handle stuff. Since manipulating depencies on the go seems to be a non trivial task, I close this issue and wait if somebody shows up with a proper implementation rather than asking for it.
